CREATE TABLE IF NOT EXISTS `users` (
  id VARCHAR(36) NOT NULL,
  username VARCHAR(30) UNIQUE NOT NULL,
  password VARCHAR(50) DEFAULT NULL,
  role ENUM('ADMIN', 'EDITOR', 'AUTHOR', 'STUDENT', 'SUPERVISOR', 'STAFF', 'TA') DEFAULT NULL,
  added DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login DATETIME DEFAULT NULL,
  last_seen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_online BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  added_by VARCHAR(40) DEFAULT NULL,
  ci_session INT DEFAULT NULL,
  session_id VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
);

