UPDATE users 
SET role = 'SUPERVISOR' 
WHERE role IN ('EXECUTIVE', 'BEYONDER');

ALTER TABLE users
MODIFY COLUMN role ENUM('ADMIN', 'EDITOR', 'AUTHOR', 'STUDENT', 'SUPERVISOR', 'STAFF', 'TA') DEFAULT NULL;
