services:
  ipca-api:
    container_name: ipca-api
    build: .
    ports:
      - ${SERVER_EXPOSE_PORT}:${SERVER_PORT}
    restart: on-failure
    volumes:
      - ./:/app/
    env_file:
      - .env
    networks:
      - ipca-stack
    privileged: true
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined

networks:
  ipca-stack:
    external: true
