services:
  ipca-api:
    container_name: ipca-api
    build: .
    ports:
      - ${BACKEND_SERVER_EXPOSE_PORT}:${BACKEND_SERVER_PORT}
    restart: unless-stopped
    environment:
      SERVER_EXPOSE_PORT: ${BACKEND_SERVER_EXPOSE_PORT}
      SERVER_PORT: ${BACKEND_SERVER_PORT}
      SERVER_HOST: ${BACKEND_SERVER_HOST}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DRIVER: ${DB_DRIVER}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_QUEUENAME: ${RABBITMQ_QUEUENAME}
      MINIO_HOST: ${MINIO_HOST}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_BUCKET_PROFILE: ${MINIO_BUCKET_PROFILE}
      MINIO_BUCKET_STUDENT_CODE: ${MINIO_BUCKET_STUDENT_CODE}
      MINIO_BUCKET_SUPERVISOR_CODE: ${MINIO_BUCKET_SUPERVISOR_CODE}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      ACCESS_SECRET: ${ACCESS_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
    networks:
      - ipca-stack
    privileged: true
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    depends_on:
      - ipca-mysql
      - rabbitmq

networks:
  ipca-stack:
    external: true
