services:
  ipca-api:
    container_name: ipca-api
    build: .
    ports:
      - ${SERVER_EXPOSE_PORT}:${SERVER_PORT}
    restart: on-failure
    volumes:
      - ./:/app/
    depends_on:
      - ipca-mysql
      - rabbitmq
      - redis
    env_file:
      - .env
    environment:
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/${DB_NAME}?charset=utf8mb4&parseTime=True&loc=Local"
    networks:
      - ipca-stack
    privileged: true
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined

  ipca-mysql:
    image: mysql:8.0
    container_name: ipca-db
    ports:
      - ${DB_EXPOSE_PORT}:${DB_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - ipca-stack
  
  redis:
    image: redis:7.0.15-alpine
    container_name: ipca-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_EXPOSE_PORT}:${REDIS_PORT}"
    networks:
      - ipca-stack
    
  rabbitmq:
    image: rabbitmq:3.12.11-management-alpine
    container_name: ipca-rabbitmq
    tty: true
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      TZ: Asia/Bangkok
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER} # Set default RabbitMQ user
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD} # Set default RabbitMQ password
    volumes:
      - rabbitmq-data-ipca:/var/lib/rabbitmq
    depends_on:
      - ipca-mysql
    networks:
      - ipca-stack

volumes:
  database_mysql:
  rabbitmq-data-ipca:

networks:
  ipca-stack:
    name: ipca-stack
    driver: bridge
