services:
  ipca-api:
    container_name: ipca-api
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - ${BACKEND_SERVER_EXPOSE_PORT}:${BACKEND_SERVER_PORT}
    restart: on-failure
    env_file:
      - .env
    environment:
      SERVER_PORT: ${BACKEND_SERVER_PORT}
      SERVER_HOST: ${BACKEND_SERVER_HOST}
    networks:
      - ipca-stack
    privileged: true
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined

networks:
  ipca-stack:
    external: true
